import Link from 'next/link';
import {
  Activity, ArrowDownRight, ArrowRight, ArrowUpRight, Atom, BookOpen, BrainCircuit, Check, ChevronRight, CircleDot,
  Command, Compass, Cpu, FlaskConical, GitBranch, Layers3, MoveUpRight, Radar, ShieldCheck,
  Sparkles, Terminal, Workflow, Zap,
} from 'lucide-react';
import { Brand } from '@/components/brand';

const proofPoints = ['Project-based skill evidence', 'Adaptive practice', 'One connected engineering workspace'];

function DashboardPreview() {
  return <div className="hero-product-frame" aria-label="NEXORA workspace product preview">
    <div className="preview-window-bar"><div className="window-dots"><span /><span /><span /></div><div className="preview-address"><span className="preview-lock">⌑</span> app.nexora.dev <span className="preview-address-path">/ dashboard</span></div><div className="preview-window-actions"><span /><span /><span /></div></div>
    <div className="preview-app">
      <aside className="preview-sidebar">
        <div className="preview-brand"><span className="preview-brand-mark"><span /></span><b>NEXORA<span>.</span></b></div>
        <div className="preview-profile"><span className="preview-avatar">A</span><div><b>Alex Morgan</b><small>Computer Science</small></div><span className="preview-caret">⌄</span></div>
        <div className="preview-nav-group"><small>WORKSPACE</small><span className="preview-nav-item is-selected"><i>◈</i>Overview</span><span className="preview-nav-item"><i>▧</i>Learning path</span><span className="preview-nav-item"><i>⌗</i>Practice</span></div>
        <div className="preview-nav-group"><small>BUILD</small><span className="preview-nav-item"><i>▱</i>Projects</span><span className="preview-nav-item preview-ai-link"><i>✳</i>AI Engineer <em /></span><span className="preview-nav-item"><i>◉</i>Skill graph</span></div>
        <div className="preview-sidebar-bottom"><div className="preview-plan"><span><Sparkles size={12} /> Free plan</span><div className="preview-mini-bar"><i /></div><small>18 of 25 AI requests</small></div><span className="preview-small-avatar">A</span><span className="preview-sidebar-name">Alex Morgan</span></div>
      </aside>
      <div className="preview-main">
        <div className="preview-topbar"><span>Workspace&nbsp; / &nbsp;<b>Overview</b></span><span className="preview-top-actions"><span>⌘ K</span><span className="preview-notification">●</span></span></div>
        <div className="preview-body">
          <div className="preview-welcome"><div><span className="preview-date">MONDAY, MAY 19, 2025 <span>•</span> WEEK 04</span><h3>Good morning, Alex <span>✳</span></h3><p>Your next engineering win is one focused session away.</p></div><span className="preview-streak"><Zap size={13} /> 6 day streak</span></div>
          <div className="preview-metric-row"><div className="preview-metric preview-progress-metric"><div className="preview-card-label">ENGINEERING PROGRESS <span>↗</span></div><div className="preview-progress-flex"><div className="preview-ring"><span>68<small>%</small></span></div><div><b>On your way</b><small>12% ahead of your pace</small><span className="preview-green-note">+12.4% <small>this month</small></span></div></div></div><div className="preview-metric preview-skill-metric"><div className="preview-card-label">SKILL MOMENTUM <span>•••</span></div><div className="preview-skill-bars"><div><span>Python</span><i><b style={{ width: '82%' }} /></i><small>82</small></div><div><span>SQL</span><i><b style={{ width: '61%' }} /></i><small>61</small></div><div><span>React</span><i><b style={{ width: '48%' }} /></i><small>48</small></div><div><span>Git</span><i><b style={{ width: '73%' }} /></i><small>73</small></div></div></div></div>
          <div className="preview-lower-row"><div className="preview-roadmap"><div className="preview-card-heading"><div><div className="preview-card-label">YOUR LEARNING PATH</div><b>Full-stack foundations</b></div><span>View all <ArrowUpRight size={11} /></span></div><div className="preview-roadmap-list"><div className="preview-roadmap-step completed"><span className="preview-step-dot">✓</span><div><b>JavaScript essentials</b><small>8 topics · 3h 20m</small></div><i>Complete</i></div><div className="preview-roadmap-step active"><span className="preview-step-dot">02</span><div><b>Build with React</b><small>5 topics · 2h 10m</small></div><i>In progress</i></div><div className="preview-roadmap-step"><span className="preview-step-dot">03</span><div><b>Design REST APIs</b><small>4 topics · 1h 45m</small></div><i>Next up</i></div></div></div><div className="preview-project"><div className="preview-card-heading"><div><div className="preview-card-label">ACTIVE PROJECT <span className="preview-live-dot" /></div><b>Campus energy monitor</b></div><span className="preview-project-more">•••</span></div><div className="preview-project-art"><div className="preview-art-grid" /><div className="preview-art-node preview-art-node-a"><Zap size={13} /></div><div className="preview-art-node preview-art-node-b"><Radar size={13} /></div><div className="preview-art-node preview-art-node-c"><Workflow size={13} /></div><span className="preview-art-line line-a" /><span className="preview-art-line line-b" /><div className="preview-art-center">◈</div><span className="preview-art-caption">SYSTEM ARCHITECTURE <i>LIVE</i></span></div><div className="preview-project-bottom"><div><span>3 of 7 milestones</span><b>43%</b></div><div className="preview-project-bar"><i /></div><small><Sparkles size={11} /> AI insight <span>Consider adding an energy baseline.</span></small></div></div></div>
        </div>
      </div>
    </div>
  </div>;
}

export default function HomePage() {
  return <main className="landing-page">
    <div className="landing-grid-glow" />
    <header className="landing-header">
      <Link className="landing-brand" href="/"><Brand /></Link>
      <nav className="landing-nav" aria-label="Main"><a href="#platform">Platform</a><a href="#workflow">How it works</a><a href="#projects">Project builder</a><Link href="/pricing">Pricing</Link></nav>
      <div className="landing-header-actions"><Link className="landing-login" href="/login">Log in</Link><Link className="button button--primary button--sm landing-header-cta" href="/register">Start building <ArrowRight size={14} /></Link></div>
    </header>

    <section className="landing-hero">
      <div className="hero-copy">
        <div className="hero-pill"><span className="hero-pill-icon"><Sparkles size={12} /></span> YOUR ENGINEERING OPERATING SYSTEM <span className="hero-pill-spark">✦</span></div>
        <h1>Turn knowledge<br />into <span>engineering.</span></h1>
        <p className="hero-subtitle">Learn smarter. Build real projects. Master practical skills. Let AI guide your journey from your first concept to your next opportunity.</p>
        <div className="hero-actions"><Link className="button button--primary button--lg" href="/register">Start building free <ArrowRight size={16} /></Link><a className="hero-secondary-link" href="#platform"><span className="hero-play-icon">▷</span> Explore NEXORA</a></div>
        <div className="hero-trust-row"><div className="hero-avatar-stack"><span>A</span><span>R</span><span>K</span><span>+</span></div><div><div className="hero-stars">✦ ✦ ✦ ✦ ✦</div><p>Built for the way engineers learn</p></div></div>
        <div className="hero-proof-points">{proofPoints.map((point) => <span key={point}><Check size={13} />{point}</span>)}</div>
      </div>
      <div className="hero-visual"><div className="hero-orbit orbit-one" /><div className="hero-orbit orbit-two" /><div className="hero-orbit-core" /><div className="hero-float-card hero-float-card--top"><span className="float-card-icon"><Sparkles size={13} /></span><div><small>AI FIELD NOTE</small><b>Strong in Python.<br />Try SQL joins next.</b></div><span className="float-card-spark">✧</span></div><div className="hero-float-card hero-float-card--right"><span className="float-card-check"><Check size={12} /></span><div><small>PROJECT EVIDENCE</small><b>+2 skills surfaced</b></div></div><DashboardPreview /><div className="hero-visual-caption"><span className="caption-line" /> A workspace that moves you forward <span className="caption-line" /></div></div>
    </section>

    <section className="proof-strip" aria-label="NEXORA capabilities"><span>ONE CONNECTED SYSTEM</span><i /><span><BookOpenIcon /> Learn with direction</span><i /><span><GitBranch size={16} /> Build with purpose</span><i /><span><Radar size={16} /> Show what you know</span></section>

    <section className="section transformation-section" id="workflow">
      <div className="section-kicker"><span>01</span> THE ENGINEERING LOOP</div>
      <div className="transformation-heading"><h2>Learning is only the<br />beginning<span>.</span></h2><p>NEXORA closes the gap between consuming knowledge and demonstrating what you can do with it.</p></div>
      <div className="loop-track"><div className="loop-line" /><div className="loop-step"><span className="loop-icon loop-icon--blue"><BookOpen size={20} /></span><strong>Learn</strong><small>Structured knowledge<br />for your discipline</small></div><span className="loop-chevron">→</span><div className="loop-step"><span className="loop-icon loop-icon--purple"><Activity size={20} /></span><strong>Practice</strong><small>Adaptive questions<br />that target weak spots</small></div><span className="loop-chevron">→</span><div className="loop-step"><span className="loop-icon loop-icon--lime"><Workflow size={20} /></span><strong>Build</strong><small>Real projects, planned<br />and broken into steps</small></div><span className="loop-chevron">→</span><div className="loop-step"><span className="loop-icon loop-icon--orange"><Radar size={20} /></span><strong>Prove</strong><small>Project evidence<br />becomes your signal</small></div><span className="loop-chevron">→</span><div className="loop-step"><span className="loop-icon loop-icon--blue"><ArrowUpRight size={20} /></span><strong>Grow</strong><small>Turn capability into<br />career momentum</small></div></div>
    </section>

    <section className="platform-section section" id="platform">
      <div className="platform-head"><div><div className="section-kicker"><span>02</span> THE NEXORA WORKSPACE</div><h2>One system.<br /><span>Every next step.</span></h2></div><p>Your notes, practice, projects, and growth don’t live in separate tabs anymore. NEXORA connects them into an engineering practice that compounds.</p></div>
      <div className="platform-grid">
        <article className="platform-card platform-card--learn"><div className="platform-card-top"><span className="platform-icon platform-icon--blue"><Compass size={17} /></span><span className="platform-number">01 / LEARN</span></div><h3>A path with<br />a point of view.</h3><p>Start with curated concepts across engineering branches. Build a path around your goals, level, and time—not an endless content feed.</p><div className="learn-path-mini"><div className="learn-path-line" /><div className="learn-path-item done"><span>✓</span><div><b>Functions & modules</b><small>12 min · complete</small></div></div><div className="learn-path-item current"><span>02</span><div><b>Data structures</b><small>18 min · in progress</small></div><i>CONTINUE</i></div><div className="learn-path-item"><span>03</span><div><b>Build a useful script</b><small>Project milestone</small></div></div></div><Link className="platform-card-link" href="/register">Explore learning <ArrowUpRight size={15} /></Link></article>
        <article className="platform-card platform-card--build" id="projects"><div className="platform-card-top"><span className="platform-icon platform-icon--lime"><Workflow size={17} /></span><span className="platform-number">02 / BUILD</span></div><h3>Real briefs.<br />Buildable plans.</h3><p>Turn an idea into architecture, milestones, tests, and a budget with clear assumptions. Start with a transparent blueprint; connect your AI provider for generation.</p><div className="build-plan-mini"><div className="build-plan-header"><span><span className="build-live" /> PROJECT BRIEF</span><small>01 — 06 WEEKS</small></div><b>Smart agriculture monitor</b><div className="build-plan-skills"><span>ESP32</span><span>Sensor systems</span><span>Python</span></div><div className="build-plan-milestones"><span><i>01</i> Calibrate field sensors</span><span><i>02</i> Build a secure data path</span><span><i>03</i> Validate & prepare a pilot</span></div><div className="build-plan-footer"><span>5 milestones</span><span>Architecture included <Check size={12} /></span></div></div><Link className="platform-card-link" href="/register">Open project builder <ArrowUpRight size={15} /></Link></article>
        <article className="platform-card platform-card--evidence"><div className="platform-card-top"><span className="platform-icon platform-icon--purple"><Radar size={17} /></span><span className="platform-number">03 / SHOW</span></div><h3>Skills need<br />proof, not guesses.</h3><p>Keep self-reported interests separate from practice scores and project evidence. Nothing is labeled verified without an actual assessment.</p><div className="evidence-graph-mini"><svg viewBox="0 0 390 160" aria-label="Illustration of connected engineering skills"><defs><linearGradient id="graphLine" x1="0" x2="1"><stop stopColor="#b9f867" stopOpacity=".15" /><stop offset="1" stopColor="#64ddce" stopOpacity=".8" /></linearGradient></defs><path d="M72 83 L147 43 L224 80 L305 38 M147 43 L165 128 L224 80 L302 119 M72 83 L165 128" stroke="url(#graphLine)" fill="none" strokeWidth="1.3" strokeDasharray="3 4"/><circle cx="72" cy="83" r="18" fill="#1f2b23" stroke="#c3fb6a" strokeWidth="1.4"/><circle cx="147" cy="43" r="16" fill="#141d29" stroke="#719dff"/><circle cx="224" cy="80" r="21" fill="#1b2525" stroke="#66d9c2" strokeWidth="1.5"/><circle cx="305" cy="38" r="13" fill="#171d2a" stroke="#9a8cff"/><circle cx="165" cy="128" r="13" fill="#1f2b23" stroke="#c3fb6a"/><circle cx="302" cy="119" r="16" fill="#201c2a" stroke="#a293ff"/><text x="72" y="86" textAnchor="middle" fill="#d5f6a0" fontSize="8">PY</text><text x="147" y="46" textAnchor="middle" fill="#a9c5ff" fontSize="8">SQL</text><text x="224" y="83" textAnchor="middle" fill="#9ce8d2" fontSize="8">IoT</text><text x="305" y="41" textAnchor="middle" fill="#c2b9ff" fontSize="7">API</text><text x="165" y="131" textAnchor="middle" fill="#d5f6a0" fontSize="7">GIT</text><text x="302" y="122" textAnchor="middle" fill="#c2b9ff" fontSize="7">HW</text></svg><div className="evidence-label evidence-label--one"><i /> Python <span>Practice · 78</span></div><div className="evidence-label evidence-label--two"><i /> IoT <span>Project evidence</span></div><div className="evidence-label evidence-label--three"><i /> SQL <span>Developing</span></div></div><Link className="platform-card-link" href="/register">See your skill graph <ArrowUpRight size={15} /></Link></article>
      </div>
    </section>

    <section className="ai-quote-section section">
      <div className="ai-quote-orb" />
      <div className="ai-quote-copy"><div className="section-kicker"><span>03</span> AI THAT MOVES WORK FORWARD</div><h2>Not another chat.<br /><span>A better next step.</span></h2><p>Every NEXORA AI action is shaped around an outcome: a clearer explanation, a debugging path, a project plan, or a useful reflection.</p><Link className="text-arrow-link" href="/register">Meet your engineering copilot <ArrowRight size={16} /></Link></div>
      <div className="ai-response-card"><div className="ai-response-header"><span className="ai-response-avatar"><Sparkles size={13} /></span><div><b>NEXORA ENGINEER</b><small>Debugging · REST API</small></div><span className="ai-generated-badge">AI GENERATED</span></div><div className="ai-response-context"><span>POST</span> /api/projects <i>·</i> 400 Bad Request</div><div className="ai-response-section"><b><span>01</span> Root cause</b><p>Your route expects <code>project_name</code>, but the form submits <code>title</code>. The schema rejects the body before the handler runs.</p></div><div className="ai-response-section"><b><span>02</span> Fix path</b><p>Align the field name at the client boundary or transform the request before validation. Keep the schema as the source of truth.</p></div><div className="ai-response-footer"><span><CircleDot size={12} /> Based on the request you shared</span><button aria-label="Copy answer"><span>↗</span></button></div></div>
    </section>

    <section className="discipline-section section"><div className="discipline-heading"><div><div className="section-kicker"><span>04</span> ENGINEERING IS BIGGER THAN CODE</div><h2>Built for every<br />kind of engineer<span>.</span></h2></div><p>Structured learning starts across disciplines, with a data model designed to grow alongside the next generation of engineering tools.</p></div><div className="discipline-row"><span><Terminal size={16} /> Computer science</span><span><Cpu size={16} /> Electronics</span><span><Zap size={16} /> Electrical</span><span><Layers3 size={16} /> Mechanical</span><span><Workflow size={16} /> Civil</span><span><BrainCircuit size={16} /> AI & data</span><span><FlaskConical size={16} /> Chemical</span><span className="discipline-more">More disciplines <ArrowRight size={13} /></span></div></section>

    <section className="final-cta section"><div className="final-cta-inner"><div className="final-cta-lines" /><div className="final-cta-copy"><span className="final-cta-spark"><Sparkles size={15} /></span><div className="section-kicker">THE NEXT STEP IS YOURS</div><h2>Build something<br />worth showing.</h2><p>Start free. Pick a topic. Make one project real. Let your work become your strongest introduction.</p><Link className="button button--primary button--lg" href="/register">Create your free workspace <ArrowRight size={16} /></Link></div><div className="final-cta-visual"><div className="cta-ring cta-ring--outer" /><div className="cta-ring cta-ring--inner" /><div className="cta-ring-core"><span>NX</span></div><div className="cta-orbit-label cta-label-a"><BookOpen size={13} /> LEARN</div><div className="cta-orbit-label cta-label-b"><Workflow size={13} /> BUILD</div><div className="cta-orbit-label cta-label-c"><Radar size={13} /> PROVE</div></div></div></section>

    <footer className="landing-footer"><Link href="/" className="footer-brand"><Brand /></Link><span>From learning to building.</span><div><Link href="/pricing">Pricing</Link><Link href="/login">Sign in</Link><a href="mailto:hello@nexora.app">Contact</a></div><small>© {new Date().getFullYear()} NEXORA. Built for engineering progress.</small></footer>
  </main>;
}

function BookOpenIcon() { return <Compass size={16} />; }
