import Link from 'next/link';
import { ArrowRight, ArrowUpRight, BriefcaseBusiness, CheckCircle2, CircleHelp, Code2, Compass, FileCode2, Gauge, Layers3, Sparkles, Target, TrendingUp } from 'lucide-react';
import { getCurrentUser } from '@/lib/auth';
import { query } from '@/lib/db';
import { masteryBand } from '@/lib/mastery';
import { Badge, Card, ProgressBar } from '@/components/ui';

export const metadata = { title: 'Skill graph' };

type Skill = { id: string; name: string; category: string; description: string; mastery: number; self_reported: boolean; evidence_count: number; project_count: number; practice_count: number; last_evidence: string | null };
type EvidenceRow = { id: string; skill_name: string; source_type: string; evidence: string; confidence: number; project_id: string | null; project_title: string | null; created_at: string };

const nextSteps: Record<string, string> = { Python: '/learn/python-functions', SQL: '/learn/sql-joins', 'API Design': '/learn/http-rest', Git: '/learn/git-workflow', Thermodynamics: '/learn/thermodynamics-first-law', 'Fluid Mechanics': '/learn/fluid-continuity', 'Circuit Analysis': '/learn/circuit-ohms-law', 'Embedded Systems': '/learn/embedded-sensors', CAD: '/learn/cad-design-intro', 'Structural Analysis': '/learn/civil-load-path', 'Machine Learning': '/learn/ml-train-test' };

export default async function SkillsPage() {
  const user = await getCurrentUser();
  if (!user) return null;
  const [skillsResult, evidenceResult] = await Promise.all([
    query<Skill>(
      `SELECT s.id,s.name,s.category,s.description,us.mastery,us.self_reported,
       COUNT(DISTINCT e.id)::int AS evidence_count,
       COUNT(DISTINCT e.project_id) FILTER (WHERE e.project_id IS NOT NULL)::int AS project_count,
       COUNT(DISTINCT e.id) FILTER (WHERE e.source_type='practice')::int AS practice_count,
       MAX(e.created_at) AS last_evidence
       FROM user_skills us JOIN skills s ON s.id=us.skill_id
       LEFT JOIN skill_evidence e ON e.skill_id=s.id AND e.user_id=us.user_id
       WHERE us.user_id=$1 GROUP BY s.id,s.name,s.category,s.description,us.mastery,us.self_reported
       ORDER BY us.mastery DESC,s.name`, [user.id]),
    query<EvidenceRow>(
      `SELECT e.id,s.name AS skill_name,e.source_type,e.evidence,e.confidence,e.project_id,p.title AS project_title,e.created_at
       FROM skill_evidence e JOIN skills s ON s.id=e.skill_id LEFT JOIN projects p ON p.id=e.project_id AND p.user_id=e.user_id
       WHERE e.user_id=$1 ORDER BY e.created_at DESC LIMIT 12`, [user.id]),
  ]);
  const skills = skillsResult.rows;
  const evidence = evidenceResult.rows;
  const average = skills.length ? Math.round(skills.reduce((total, skill) => total + skill.mastery, 0) / skills.length) : 0;
  const projectEvidence = evidence.filter((item) => item.source_type === 'project').length;
  const practiceEvidence = evidence.filter((item) => item.source_type === 'practice').length;
  const categories = Array.from(new Set(skills.map((skill) => skill.category)));
  return <div className="page-stack skills-page"><div className="page-hero-row"><div><div className="page-kicker"><Layers3 size={13} /> SKILL GRAPH <span className="page-kicker-divider">·</span> EVIDENCE, NOT LABELS</div><h1>See what you’re<br />building<span className="welcome-period">.</span></h1><p className="dashboard-intro">Self-reported interests, practice signals, and project artifacts remain distinct—so your growth is useful and honest.</p></div><div className="skill-readiness-card"><span className="skill-readiness-icon"><Gauge size={16} /></span><div><small>ESTIMATED MASTERY</small><strong>{average}<span>/ 100</span></strong><span className="readiness-note">From {skills.length} tracked skills · not a credential</span></div></div></div>
    <div className="skill-evidence-summary"><div><span className="evidence-summary-icon evidence-summary-icon--project"><BriefcaseBusiness size={14} /></span><div><strong>{projectEvidence}</strong><small>project evidence items</small></div></div><div><span className="evidence-summary-icon evidence-summary-icon--practice"><Target size={14} /></span><div><strong>{practiceEvidence}</strong><small>practice signals</small></div></div><div><span className="evidence-summary-icon evidence-summary-icon--self"><Compass size={14} /></span><div><strong>{skills.filter((skill) => skill.self_reported).length}</strong><small>self-reported skills</small></div></div><div className="summary-disclaimer"><CircleHelp size={13} /> Evidence supports reflection. It does not independently verify competency.</div></div>
    {skills.length ? <><Card className="skill-network-card"><div className="skill-network-header"><div><span className="card-eyebrow"><Sparkles size={13} /> YOUR ENGINEERING SIGNAL</span><h2>A living map of your practice.</h2><p>Each node links to a skill with evidence from your own workspace.</p></div><Badge tone="lime">{skills.length} TRACKED</Badge></div><SkillNetwork skills={skills.slice(0, 8)} /><div className="skill-network-legend"><span><i className="legend-dot legend-dot--project" /> Project evidence</span><span><i className="legend-dot legend-dot--practice" /> Practice mastery</span><span><i className="legend-dot legend-dot--self" /> Self-reported</span></div></Card>
    <div className="skill-category-list">{categories.map((category) => <section className="skill-category-section" key={category}><div className="skill-category-heading"><span className="skill-category-icon"><Code2 size={15} /></span><div><span className="card-eyebrow">{category.toUpperCase()}</span><h2>{skills.filter((skill) => skill.category === category).length} {category === 'Self-reported technology' ? 'interests' : 'skills'}</h2></div><span className="skill-category-divider" /></div><div className="skill-category-grid">{skills.filter((skill) => skill.category === category).map((skill, index) => <Card className="skill-detail-card" key={skill.id}><div className="skill-detail-top"><span className={`skill-detail-node skill-detail-node--${index % 4}`}><span /></span><Badge tone={skill.self_reported ? 'neutral' : skill.mastery > 60 ? 'lime' : 'blue'}>{skill.self_reported ? 'SELF-REPORTED' : masteryBand(skill.mastery).toUpperCase()}</Badge><span className="skill-detail-more" aria-hidden="true"><ArrowUpRight size={15} /></span></div><h3>{skill.name}</h3><p>{skill.description}</p><div className="skill-detail-meter"><div><span>{skill.self_reported ? 'Learner-selected starting point' : 'Estimated mastery'}</span><strong>{skill.mastery}<small>/100</small></strong></div><ProgressBar value={skill.mastery} color={index % 3 === 0 ? 'lime' : index % 3 === 1 ? 'blue' : 'purple'} /></div><div className="skill-detail-evidence-row"><span><CheckCircle2 size={12} /> {skill.evidence_count} evidence</span><span><BriefcaseBusiness size={12} /> {skill.project_count} projects</span><span><Target size={12} /> {skill.practice_count} practice</span></div><div className="skill-next-step">{skill.self_reported ? <span><Compass size={12} /> Self-reported by you; not assessed yet.</span> : <span><TrendingUp size={12} /> Next step: {nextSteps[skill.name] ? 'review a concept, then practice' : 'add more project or practice evidence'}</span>}{nextSteps[skill.name] && <Link href={nextSteps[skill.name]}>Go <ArrowRight size={12} /></Link>}</div></Card>)}</div></section>)}</div>
    <Card className="skill-evidence-feed"><div className="skill-feed-heading"><div><span className="card-eyebrow"><FileCode2 size={13} /> EVIDENCE TRAIL</span><h2>What this graph is based on.</h2></div><span className="skill-feed-note">Recent items · newest first</span></div>{evidence.length ? <div className="skill-evidence-list">{evidence.map((item) => <div className="skill-evidence-item" key={item.id}><span className={`skill-evidence-icon skill-evidence-icon--${item.source_type}`} >{item.source_type === 'project' ? <BriefcaseBusiness size={14} /> : item.source_type === 'practice' ? <Target size={14} /> : <BookOpenIcon />}</span><div className="skill-evidence-copy"><div><strong>{item.skill_name}</strong><Badge tone={item.source_type === 'project' ? 'orange' : item.source_type === 'practice' ? 'blue' : 'neutral'}>{item.source_type.replace('_', ' ').toUpperCase()}</Badge><small>{new Date(item.created_at).toLocaleDateString('en', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' })}</small></div><p>{item.evidence}</p>{item.project_title && <Link href={`/projects/${item.project_id}`}>{item.project_title} <ArrowUpRight size={12} /></Link>}</div><span className="evidence-confidence">{item.confidence}% <small>signal</small></span></div>)}</div> : <div className="skill-evidence-empty"><Sparkles size={17} /><strong>Your evidence trail starts with doing.</strong><p>Practice a concept or add a real artifact to a project. A selected technology is only labeled self-reported.</p><div><Link href="/practice">Practice a topic <ArrowRight size={13} /></Link><Link href="/projects">Open projects <ArrowRight size={13} /></Link></div></div>}</Card></> : <Card className="skill-graph-empty"><div className="empty-graph-orbit"><span><Layers3 size={19} /></span><i /><b /><em /></div><span className="card-eyebrow">NO SKILLS TRACKED YET</span><h2>Evidence starts with one attempt.</h2><p>Choose a learning topic, answer a few questions, or add a real project artifact. Your graph will grow from actual activity—not assumed ability.</p><div><Link className="button button--primary" href="/practice">Start practice <ArrowRight size={14} /></Link><Link className="button button--secondary" href="/projects">Build a project <ArrowRight size={14} /></Link></div></Card>}
  </div>;
}

function SkillNetwork({ skills }: { skills: Skill[] }) {
  const positions = [
    { x: 100, y: 104 }, { x: 270, y: 60 }, { x: 430, y: 102 }, { x: 600, y: 62 },
    { x: 210, y: 235 }, { x: 390, y: 218 }, { x: 565, y: 225 }, { x: 730, y: 134 },
  ];
  const points = skills.map((skill, index) => ({ ...skill, ...(positions[index] || positions[7]) }));
  const edges = [[0, 1], [1, 2], [2, 3], [0, 4], [1, 4], [1, 5], [2, 5], [2, 6], [3, 7], [5, 6], [6, 7]];
  return <div className="skill-network-visual"><svg viewBox="0 0 830 300" role="img" aria-label={`Skill evidence map with ${skills.length} skills`}><defs><linearGradient id="skillEdge" x1="0" x2="1"><stop stopColor="#8b9aa0" stopOpacity=".1" /><stop offset=".5" stopColor="#93dcad" stopOpacity=".4" /><stop offset="1" stopColor="#9389ff" stopOpacity=".2" /></linearGradient><filter id="skillGlow"><feGaussianBlur stdDeviation="7" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter></defs>{edges.filter(([from, to]) => from < points.length && to < points.length).map(([from, to]) => <line key={`${from}-${to}`} x1={points[from].x} y1={points[from].y} x2={points[to].x} y2={points[to].y} stroke="url(#skillEdge)" strokeWidth="1.4" strokeDasharray="4 5" />)}{points.map((skill, index) => { const radius = 20 + Math.round(skill.mastery / 9); const color = skill.self_reported ? '#8a94a2' : skill.project_count ? '#c7f36b' : '#72caff'; return <g key={skill.id} className="skill-svg-node"><circle cx={skill.x} cy={skill.y} r={radius + 8} fill={color} opacity=".04" filter="url(#skillGlow)" /><circle cx={skill.x} cy={skill.y} r={radius} fill="#0e161b" stroke={color} strokeOpacity=".72" strokeWidth="1.5" /><circle cx={skill.x} cy={skill.y} r={Math.max(4, radius * skill.mastery / 100)} fill={color} fillOpacity=".17" /><text x={skill.x} y={skill.y + 4} textAnchor="middle" fill="#edf1e9" fontSize="10" fontWeight="600">{skill.name.length > 11 ? `${skill.name.slice(0, 10)}…` : skill.name}</text><text x={skill.x} y={skill.y + radius + 18} textAnchor="middle" fill="#87949a" fontSize="9">{skill.self_reported ? 'SELF-REPORTED' : skill.project_count ? 'PROJECT EVIDENCE' : 'PRACTICE SIGNAL'}</text></g>; })}</svg><div className="skill-network-floating"><span><i /> LIVE SKILL MAP</span><b>{skills.length}<small> nodes</small></b><p>Strength is inferred from your own evidence.</p></div></div>;
}

function BookOpenIcon() { return <span aria-hidden="true">◫</span>; }
