'use client';

import Link from 'next/link';
import { useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRight, ArrowUpRight, BriefcaseBusiness, Check, CircleHelp, FileText, Globe2, LoaderCircle, LockKeyhole, Mail, ShieldCheck, UserRound } from 'lucide-react';
import { Badge, Button, Card } from './ui';

type Profile = { username: string; headline: string; about: string; is_public: boolean; show_email: boolean; show_resume: boolean };
type Project = { id: string; title: string; description: string; status: string; visibility: string; evidence_count: number; evidence_names: string; skill_names: string };
type Skill = { name: string; mastery: number; evidence_count: number; self_reported: boolean };
type UserProfile = { name: string; email: string; branch: string | null; currentYear: string | null };

export function PortfolioBuilder({ profile, user, projects, skills, hasResume }: { profile: Profile; user: UserProfile; projects: Project[]; skills: Skill[]; hasResume: boolean }) {
  const router = useRouter();
  const [username, setUsername] = useState(profile.username);
  const [headline, setHeadline] = useState(profile.headline);
  const [about, setAbout] = useState(profile.about);
  const [isPublic, setIsPublic] = useState(profile.is_public);
  const [showEmail, setShowEmail] = useState(profile.show_email);
  const [showResume, setShowResume] = useState(profile.show_resume && hasResume);
  const [publicProjectIds, setPublicProjectIds] = useState(projects.filter((project) => project.visibility === 'public').map((project) => project.id));
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  function toggleProject(id: string) { setPublicProjectIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); }
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError(''); setSuccess('');
    try {
      const response = await fetch('/api/portfolio', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ username, headline, about, isPublic, showEmail, showResume, publicProjectIds }) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to save portfolio settings.');
      setSuccess(isPublic ? 'Portfolio published. Only the items you selected are visible.' : 'Portfolio saved privately.'); router.refresh();
    } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save portfolio settings.'); }
    finally { setBusy(false); }
  }
  const publicPath = `/u/${username}`;

  return <div className="portfolio-builder-layout"><div className="portfolio-editor-column"><form onSubmit={submit}><Card className="portfolio-identity-card"><div className="portfolio-editor-heading"><span className="portfolio-editor-icon"><UserRound size={16} /></span><div><span className="card-eyebrow">PUBLIC PROFILE</span><h2>How should people find you?</h2><p>Your NEXORA account email remains private unless you turn it on below.</p></div></div><label>PORTFOLIO URL<div className="portfolio-url-field"><span>nexora.app/u/</span><input value={username} onChange={(e) => setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '').slice(0, 30))} minLength={3} maxLength={30} pattern="[a-z0-9][a-z0-9-]+[a-z0-9]" required /><span className="url-availability">EDITABLE</span></div></label><label>HEADLINE <small>Optional · factual focus</small><input className="input" value={headline} onChange={(e) => setHeadline(e.target.value)} maxLength={140} placeholder={`${user.branch || 'Engineering'} learner · ${user.currentYear || 'student'}`} /></label><label>ABOUT <small>Write this in your own words</small><textarea className="input portfolio-about-input" value={about} onChange={(e) => setAbout(e.target.value)} maxLength={1000} rows={5} placeholder="What are you learning, building, or exploring? Avoid claims you cannot support." /><span className="portfolio-character-count">{about.length}/1,000</span></label></Card>
      <Card className="portfolio-project-selection"><div className="portfolio-section-heading"><span className="portfolio-editor-icon portfolio-editor-icon--blue"><BriefcaseBusiness size={16} /></span><div><span className="card-eyebrow">PROJECTS</span><h2>Select what to share.</h2><p>Each project is private until you include it and publish your portfolio.</p></div></div>{projects.length ? <div className="portfolio-project-checklist">{projects.map((project) => <label className={`portfolio-project-option${publicProjectIds.includes(project.id) ? ' is-selected' : ''}`} key={project.id}><input type="checkbox" checked={publicProjectIds.includes(project.id)} onChange={() => toggleProject(project.id)} /><span className="portfolio-option-check"><Check size={12} /></span><span className="portfolio-project-option-copy"><strong>{project.title}</strong><small>{project.evidence_count ? `${project.evidence_count} user-provided artifact${project.evidence_count === 1 ? '' : 's'} · ${project.status.replace('_', ' ')}` : `Plan only · ${project.status.replace('_', ' ')}`}</small></span><Badge tone={project.evidence_count ? 'lime' : 'neutral'}>{project.evidence_count ? 'EVIDENCE' : 'PLAN'}</Badge></label>)}</div> : <div className="portfolio-no-projects"><BriefcaseBusiness size={16} /><span>No projects in your workspace yet. <Link href="/projects/new">Start with a project brief <ArrowRight size={12} /></Link></span></div>}</Card>
      <Card className="portfolio-skills-selection"><div className="portfolio-section-heading"><span className="portfolio-editor-icon portfolio-editor-icon--purple"><FileText size={16} /></span><div><span className="card-eyebrow">SKILLS</span><h2>Evidence-backed only.</h2><p>Self-reported interests stay off the public skill list.</p></div></div>{skills.filter((skill) => !skill.self_reported && skill.evidence_count > 0).length ? <div className="portfolio-skill-pills">{skills.filter((skill) => !skill.self_reported && skill.evidence_count > 0).map((skill) => <span key={skill.name}><Check size={11} />{skill.name}<small>{skill.evidence_count} signal{skill.evidence_count === 1 ? '' : 's'}</small></span>)}</div> : <div className="portfolio-no-projects"><CircleHelp size={15} /><span>Practice a topic or analyze project artifacts to create evidence-backed skills.</span></div>}</Card>
      <Card className="portfolio-privacy-controls"><div className="portfolio-section-heading"><span className="portfolio-editor-icon portfolio-editor-icon--orange"><ShieldCheck size={16} /></span><div><span className="card-eyebrow">PRIVACY CONTROLS</span><h2>Choose your boundaries.</h2><p>Every optional detail stays off until you enable it.</p></div></div><PrivacyToggle label="Publish portfolio" detail="Anyone with your URL can view selected profile and project details." checked={isPublic} onChange={setIsPublic} icon={<Globe2 size={15} />} /><PrivacyToggle label="Show my email address" detail={user.email} checked={showEmail} onChange={setShowEmail} icon={<Mail size={15} />} /><PrivacyToggle label="Include my resume" detail={hasResume ? 'Your resume details will appear on the public page.' : 'Build a resume first; none is saved yet.'} checked={showResume} onChange={setShowResume} icon={<FileText size={15} />} disabled={!hasResume} /></Card>
      {error && <div className="form-alert form-alert--error" role="alert">{error}</div>}{success && <div className="form-alert form-alert--success" role="status"><Check size={14} />{success}</div>}<div className="portfolio-save-row"><Button type="submit" size="lg" disabled={busy}>{busy ? <><LoaderCircle className="spin-icon" size={15} /> Saving…</> : <>{isPublic ? <Globe2 size={15} /> : <LockKeyhole size={15} />} {isPublic ? 'Save & publish portfolio' : 'Save private portfolio'} <ArrowRight size={15} /></>}</Button>{isPublic && <a className="portfolio-preview-link" href={publicPath} target="_blank" rel="noreferrer">Preview public page <ArrowUpRight size={13} /></a>}</div></form></div><aside className="portfolio-preview-column"><div className="portfolio-preview-sticky"><div className="portfolio-preview-header"><div><span className="card-eyebrow">LIVE PREVIEW</span><small>{isPublic ? 'Public changes after saving' : 'Private draft preview'}</small></div><span className={`portfolio-preview-status${isPublic ? ' is-public' : ''}`}><i />{isPublic ? 'PUBLIC' : 'PRIVATE'}</span></div><PortfolioPreview user={user} username={username} headline={headline} about={about} projects={projects.filter((project) => publicProjectIds.includes(project.id))} skills={skills.filter((skill) => !skill.self_reported && skill.evidence_count > 0)} showEmail={showEmail} showResume={showResume} hasResume={hasResume} /></div></aside></div>;
}

function PrivacyToggle({ label, detail, checked, onChange, icon, disabled = false }: { label: string; detail: string; checked: boolean; onChange: (value: boolean) => void; icon: React.ReactNode; disabled?: boolean }) {
  return <label className={`portfolio-privacy-toggle${disabled ? ' is-disabled' : ''}`}><span className="privacy-toggle-icon">{icon}</span><span className="privacy-toggle-copy"><strong>{label}</strong><small>{detail}</small></span><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)} /><span className="privacy-toggle-switch" /></label>;
}

function PortfolioPreview({ user, username, headline, about, projects, skills, showEmail, showResume, hasResume }: { user: UserProfile; username: string; headline: string; about: string; projects: Project[]; skills: Skill[]; showEmail: boolean; showResume: boolean; hasResume: boolean }) {
  return <div className="public-portfolio-preview"><div className="preview-profile-cover"><div className="preview-profile-grid" /><span className="preview-cover-brand">NEXORA · ENGINEERING PORTFOLIO</span></div><div className="preview-profile-content"><div className="preview-profile-avatar">{user.name.slice(0, 1).toUpperCase()}</div><h2>{user.name}</h2><p className="preview-profile-headline">{headline || `${user.branch || 'Engineering'} learner`}</p><p className="preview-profile-location">{user.branch || 'Engineering'}{user.currentYear ? ` · ${user.currentYear}` : ''}</p>{showEmail && <a className="preview-profile-email" href={`mailto:${user.email}`}><Mail size={12} />{user.email}</a>}{about && <p className="preview-profile-about">{about}</p>}{skills.length > 0 && <div className="preview-public-skills"><span>SKILLS WITH EVIDENCE</span><div>{skills.slice(0, 8).map((skill) => <i key={skill.name}>{skill.name}</i>)}</div></div>}<div className="preview-public-projects"><div className="preview-public-project-head"><span>PROJECTS</span><b>{projects.length}</b></div>{projects.length ? projects.slice(0, 3).map((project) => <div className="preview-public-project" key={project.id}><span className="public-project-symbol"><BriefcaseBusiness size={13} /></span><div><strong>{project.title}</strong><small>{project.evidence_count ? `${project.evidence_count} artifact${project.evidence_count === 1 ? '' : 's'} · ` : 'Plan only · '}{project.status.replace('_', ' ')}</small></div></div>) : <div className="preview-public-empty">Select projects to share.</div>}</div>{showResume && hasResume && <div className="preview-resume-link"><FileText size={13} /> Resume section included</div>}<div className="preview-profile-footer"><span><span className="preview-footer-mark">NX</span> Built with NEXORA</span><span>Public only when you publish</span></div></div></div>;
}
